// قائمة كاملة بأشهر الأفعال الشاذة بالإنجليزي (Base / Past Simple / Past Participle)
// مع الترجمة العربية ومستوى الصعوبة — تُستخدم لزر "استيراد القائمة الكاملة"
// بصفحة الأفعال الشاذة، بدل ما يضطر المعلم يكتبها فعل فعل.

export interface IrregularVerbSeed {
  base: string;
  pastSimple: string;
  pastParticiple: string;
  meaningAr: string;
  level: "easy" | "medium" | "hard";
}

export const IRREGULAR_VERBS_SEED: IrregularVerbSeed[] = [
  { base: "be", pastSimple: "was/were", pastParticiple: "been", meaningAr: "يكون", level: "easy" },
  { base: "become", pastSimple: "became", pastParticiple: "become", meaningAr: "يصبح", level: "easy" },
  { base: "begin", pastSimple: "began", pastParticiple: "begun", meaningAr: "يبدأ", level: "easy" },
  { base: "break", pastSimple: "broke", pastParticiple: "broken", meaningAr: "يكسر", level: "easy" },
  { base: "bring", pastSimple: "brought", pastParticiple: "brought", meaningAr: "يحضر", level: "easy" },
  { base: "build", pastSimple: "built", pastParticiple: "built", meaningAr: "يبني", level: "medium" },
  { base: "buy", pastSimple: "bought", pastParticiple: "bought", meaningAr: "يشتري", level: "easy" },
  { base: "catch", pastSimple: "caught", pastParticiple: "caught", meaningAr: "يمسك", level: "easy" },
  { base: "choose", pastSimple: "chose", pastParticiple: "chosen", meaningAr: "يختار", level: "medium" },
  { base: "come", pastSimple: "came", pastParticiple: "come", meaningAr: "يأتي", level: "easy" },
  { base: "cost", pastSimple: "cost", pastParticiple: "cost", meaningAr: "يكلّف", level: "medium" },
  { base: "cut", pastSimple: "cut", pastParticiple: "cut", meaningAr: "يقطع", level: "easy" },
  { base: "do", pastSimple: "did", pastParticiple: "done", meaningAr: "يفعل", level: "easy" },
  { base: "draw", pastSimple: "drew", pastParticiple: "drawn", meaningAr: "يرسم", level: "medium" },
  { base: "drink", pastSimple: "drank", pastParticiple: "drunk", meaningAr: "يشرب", level: "easy" },
  { base: "drive", pastSimple: "drove", pastParticiple: "driven", meaningAr: "يقود", level: "easy" },
  { base: "eat", pastSimple: "ate", pastParticiple: "eaten", meaningAr: "يأكل", level: "easy" },
  { base: "fall", pastSimple: "fell", pastParticiple: "fallen", meaningAr: "يسقط", level: "easy" },
  { base: "feel", pastSimple: "felt", pastParticiple: "felt", meaningAr: "يشعر", level: "easy" },
  { base: "fight", pastSimple: "fought", pastParticiple: "fought", meaningAr: "يقاتل", level: "medium" },
  { base: "find", pastSimple: "found", pastParticiple: "found", meaningAr: "يجد", level: "easy" },
  { base: "fly", pastSimple: "flew", pastParticiple: "flown", meaningAr: "يطير", level: "medium" },
  { base: "forget", pastSimple: "forgot", pastParticiple: "forgotten", meaningAr: "ينسى", level: "medium" },
  { base: "forgive", pastSimple: "forgave", pastParticiple: "forgiven", meaningAr: "يسامح", level: "hard" },
  { base: "get", pastSimple: "got", pastParticiple: "gotten", meaningAr: "يحصل على", level: "easy" },
  { base: "give", pastSimple: "gave", pastParticiple: "given", meaningAr: "يعطي", level: "easy" },
  { base: "go", pastSimple: "went", pastParticiple: "gone", meaningAr: "يذهب", level: "easy" },
  { base: "grow", pastSimple: "grew", pastParticiple: "grown", meaningAr: "ينمو", level: "medium" },
  { base: "hang", pastSimple: "hung", pastParticiple: "hung", meaningAr: "يعلّق", level: "medium" },
  { base: "have", pastSimple: "had", pastParticiple: "had", meaningAr: "يملك", level: "easy" },
  { base: "hear", pastSimple: "heard", pastParticiple: "heard", meaningAr: "يسمع", level: "easy" },
  { base: "hide", pastSimple: "hid", pastParticiple: "hidden", meaningAr: "يختبئ", level: "medium" },
  { base: "hit", pastSimple: "hit", pastParticiple: "hit", meaningAr: "يضرب", level: "easy" },
  { base: "hold", pastSimple: "held", pastParticiple: "held", meaningAr: "يمسك", level: "medium" },
  { base: "hurt", pastSimple: "hurt", pastParticiple: "hurt", meaningAr: "يؤذي", level: "medium" },
  { base: "keep", pastSimple: "kept", pastParticiple: "kept", meaningAr: "يحتفظ", level: "easy" },
  { base: "know", pastSimple: "knew", pastParticiple: "known", meaningAr: "يعرف", level: "easy" },
  { base: "lay", pastSimple: "laid", pastParticiple: "laid", meaningAr: "يضع", level: "hard" },
  { base: "lead", pastSimple: "led", pastParticiple: "led", meaningAr: "يقود/يتزعّم", level: "medium" },
  { base: "learn", pastSimple: "learnt", pastParticiple: "learnt", meaningAr: "يتعلّم", level: "easy" },
  { base: "leave", pastSimple: "left", pastParticiple: "left", meaningAr: "يغادر", level: "easy" },
  { base: "lend", pastSimple: "lent", pastParticiple: "lent", meaningAr: "يُقرض", level: "medium" },
  { base: "let", pastSimple: "let", pastParticiple: "let", meaningAr: "يسمح", level: "easy" },
  { base: "lie", pastSimple: "lay", pastParticiple: "lain", meaningAr: "يستلقي", level: "hard" },
  { base: "lose", pastSimple: "lost", pastParticiple: "lost", meaningAr: "يخسر", level: "easy" },
  { base: "make", pastSimple: "made", pastParticiple: "made", meaningAr: "يصنع", level: "easy" },
  { base: "mean", pastSimple: "meant", pastParticiple: "meant", meaningAr: "يعني", level: "medium" },
  { base: "meet", pastSimple: "met", pastParticiple: "met", meaningAr: "يقابل", level: "easy" },
  { base: "pay", pastSimple: "paid", pastParticiple: "paid", meaningAr: "يدفع", level: "easy" },
  { base: "put", pastSimple: "put", pastParticiple: "put", meaningAr: "يضع", level: "easy" },
  { base: "read", pastSimple: "read", pastParticiple: "read", meaningAr: "يقرأ", level: "easy" },
  { base: "ride", pastSimple: "rode", pastParticiple: "ridden", meaningAr: "يركب", level: "medium" },
  { base: "ring", pastSimple: "rang", pastParticiple: "rung", meaningAr: "يرن", level: "medium" },
  { base: "rise", pastSimple: "rose", pastParticiple: "risen", meaningAr: "يرتفع", level: "medium" },
  { base: "run", pastSimple: "ran", pastParticiple: "run", meaningAr: "يجري", level: "easy" },
  { base: "say", pastSimple: "said", pastParticiple: "said", meaningAr: "يقول", level: "easy" },
  { base: "see", pastSimple: "saw", pastParticiple: "seen", meaningAr: "يرى", level: "easy" },
  { base: "sell", pastSimple: "sold", pastParticiple: "sold", meaningAr: "يبيع", level: "easy" },
  { base: "send", pastSimple: "sent", pastParticiple: "sent", meaningAr: "يرسل", level: "easy" },
  { base: "set", pastSimple: "set", pastParticiple: "set", meaningAr: "يضبط/يحدد", level: "medium" },
  { base: "shake", pastSimple: "shook", pastParticiple: "shaken", meaningAr: "يهز", level: "medium" },
  { base: "shine", pastSimple: "shone", pastParticiple: "shone", meaningAr: "يلمع", level: "medium" },
  { base: "shoot", pastSimple: "shot", pastParticiple: "shot", meaningAr: "يطلق النار", level: "hard" },
  { base: "show", pastSimple: "showed", pastParticiple: "shown", meaningAr: "يُظهر", level: "easy" },
  { base: "shut", pastSimple: "shut", pastParticiple: "shut", meaningAr: "يغلق", level: "medium" },
  { base: "sing", pastSimple: "sang", pastParticiple: "sung", meaningAr: "يغني", level: "easy" },
  { base: "sit", pastSimple: "sat", pastParticiple: "sat", meaningAr: "يجلس", level: "easy" },
  { base: "sleep", pastSimple: "slept", pastParticiple: "slept", meaningAr: "ينام", level: "easy" },
  { base: "speak", pastSimple: "spoke", pastParticiple: "spoken", meaningAr: "يتكلم", level: "easy" },
  { base: "spend", pastSimple: "spent", pastParticiple: "spent", meaningAr: "يصرف/يقضي وقت", level: "easy" },
  { base: "stand", pastSimple: "stood", pastParticiple: "stood", meaningAr: "يقف", level: "easy" },
  { base: "steal", pastSimple: "stole", pastParticiple: "stolen", meaningAr: "يسرق", level: "medium" },
  { base: "swim", pastSimple: "swam", pastParticiple: "swum", meaningAr: "يسبح", level: "medium" },
  { base: "take", pastSimple: "took", pastParticiple: "taken", meaningAr: "يأخذ", level: "easy" },
  { base: "teach", pastSimple: "taught", pastParticiple: "taught", meaningAr: "يعلّم", level: "easy" },
  { base: "tear", pastSimple: "tore", pastParticiple: "torn", meaningAr: "يمزق", level: "hard" },
  { base: "tell", pastSimple: "told", pastParticiple: "told", meaningAr: "يخبر", level: "easy" },
  { base: "think", pastSimple: "thought", pastParticiple: "thought", meaningAr: "يفكر", level: "easy" },
  { base: "throw", pastSimple: "threw", pastParticiple: "thrown", meaningAr: "يرمي", level: "medium" },
  { base: "understand", pastSimple: "understood", pastParticiple: "understood", meaningAr: "يفهم", level: "medium" },
  { base: "wake", pastSimple: "woke", pastParticiple: "woken", meaningAr: "يستيقظ", level: "medium" },
  { base: "wear", pastSimple: "wore", pastParticiple: "worn", meaningAr: "يلبس", level: "medium" },
  { base: "win", pastSimple: "won", pastParticiple: "won", meaningAr: "يفوز", level: "easy" },
  { base: "write", pastSimple: "wrote", pastParticiple: "written", meaningAr: "يكتب", level: "easy" },
];
