// قائمة شاملة بأكثر الأفعال الشاذة الإنجليزية شيوعًا (Base / Past Simple /
// Past Participle) مع المعنى بالعربي وجملة مثال ومستوى صعوبة تقريبي.
// هاي بيانات "مصدر" ثابتة بالكود — بتُستورد لقاعدة بيانات Firestore بضغطة
// زر واحدة من صفحة الأفعال الشاذة بلوحة تحكم المعلم، وكل فعل بينضاف
// بحالة "معطّل" افتراضيًا (active: false) حتى المعلم يختار بنفسه أي
// الأفعال يبيّنها فعليًا للطلاب (بدل ما تظهر كلها دفعة وحدة).

export type IrregularLevel = "easy" | "medium" | "hard";

export interface IrregularVerbSeed {
  base: string;
  pastSimple: string;
  pastParticiple: string;
  meaningAr: string;
  example: string;
  level: IrregularLevel;
}

export const IRREGULAR_VERBS_SEED: IrregularVerbSeed[] = [
  // ===== سهل (الأكثر استخدامًا يوميًا) =====
  { base: "be", pastSimple: "was/were", pastParticiple: "been", meaningAr: "يكون", example: "I was at school yesterday.", level: "easy" },
  { base: "have", pastSimple: "had", pastParticiple: "had", meaningAr: "يملك / لديه", example: "She had a nice bag.", level: "easy" },
  { base: "do", pastSimple: "did", pastParticiple: "done", meaningAr: "يفعل", example: "He did his homework.", level: "easy" },
  { base: "go", pastSimple: "went", pastParticiple: "gone", meaningAr: "يذهب", example: "They went to the market.", level: "easy" },
  { base: "get", pastSimple: "got", pastParticiple: "gotten", meaningAr: "يحصل على", example: "I got a new phone.", level: "easy" },
  { base: "make", pastSimple: "made", pastParticiple: "made", meaningAr: "يصنع", example: "She made a cake.", level: "easy" },
  { base: "say", pastSimple: "said", pastParticiple: "said", meaningAr: "يقول", example: "He said hello.", level: "easy" },
  { base: "see", pastSimple: "saw", pastParticiple: "seen", meaningAr: "يرى", example: "I saw a bird.", level: "easy" },
  { base: "know", pastSimple: "knew", pastParticiple: "known", meaningAr: "يعرف", example: "She knew the answer.", level: "easy" },
  { base: "take", pastSimple: "took", pastParticiple: "taken", meaningAr: "يأخذ", example: "He took my pen.", level: "easy" },
  { base: "come", pastSimple: "came", pastParticiple: "come", meaningAr: "يأتي", example: "They came late.", level: "easy" },
  { base: "think", pastSimple: "thought", pastParticiple: "thought", meaningAr: "يفكر", example: "I thought about it.", level: "easy" },
  { base: "give", pastSimple: "gave", pastParticiple: "given", meaningAr: "يعطي", example: "She gave me a gift.", level: "easy" },
  { base: "find", pastSimple: "found", pastParticiple: "found", meaningAr: "يجد", example: "He found his keys.", level: "easy" },
  { base: "eat", pastSimple: "ate", pastParticiple: "eaten", meaningAr: "يأكل", example: "We ate dinner together.", level: "easy" },
  { base: "tell", pastSimple: "told", pastParticiple: "told", meaningAr: "يخبر", example: "She told me the truth.", level: "easy" },
  { base: "put", pastSimple: "put", pastParticiple: "put", meaningAr: "يضع", example: "He put the book on the table.", level: "easy" },
  { base: "run", pastSimple: "ran", pastParticiple: "run", meaningAr: "يجري", example: "The dog ran fast.", level: "easy" },
  { base: "sit", pastSimple: "sat", pastParticiple: "sat", meaningAr: "يجلس", example: "She sat on the chair.", level: "easy" },
  { base: "stand", pastSimple: "stood", pastParticiple: "stood", meaningAr: "يقف", example: "He stood near the door.", level: "easy" },
  { base: "read", pastSimple: "read", pastParticiple: "read", meaningAr: "يقرأ", example: "I read a book last night.", level: "easy" },
  { base: "write", pastSimple: "wrote", pastParticiple: "written", meaningAr: "يكتب", example: "She wrote a letter.", level: "easy" },
  { base: "speak", pastSimple: "spoke", pastParticiple: "spoken", meaningAr: "يتحدث", example: "He spoke English well.", level: "easy" },
  { base: "hear", pastSimple: "heard", pastParticiple: "heard", meaningAr: "يسمع", example: "I heard a strange noise.", level: "easy" },
  { base: "let", pastSimple: "let", pastParticiple: "let", meaningAr: "يسمح", example: "She let me go early.", level: "easy" },
  { base: "leave", pastSimple: "left", pastParticiple: "left", meaningAr: "يغادر", example: "They left the party early.", level: "easy" },
  { base: "feel", pastSimple: "felt", pastParticiple: "felt", meaningAr: "يشعر", example: "I felt very happy.", level: "easy" },
  { base: "bring", pastSimple: "brought", pastParticiple: "brought", meaningAr: "يحضر", example: "He brought his laptop.", level: "easy" },
  { base: "buy", pastSimple: "bought", pastParticiple: "bought", meaningAr: "يشتري", example: "She bought new shoes.", level: "easy" },
  { base: "begin", pastSimple: "began", pastParticiple: "begun", meaningAr: "يبدأ", example: "The class began at nine.", level: "easy" },
  { base: "keep", pastSimple: "kept", pastParticiple: "kept", meaningAr: "يحتفظ", example: "He kept the secret.", level: "easy" },
  { base: "hold", pastSimple: "held", pastParticiple: "held", meaningAr: "يمسك", example: "She held my hand.", level: "easy" },
  { base: "meet", pastSimple: "met", pastParticiple: "met", meaningAr: "يقابل", example: "I met my friend yesterday.", level: "easy" },
  { base: "pay", pastSimple: "paid", pastParticiple: "paid", meaningAr: "يدفع", example: "He paid the bill.", level: "easy" },
  { base: "sell", pastSimple: "sold", pastParticiple: "sold", meaningAr: "يبيع", example: "She sold her old car.", level: "easy" },
  { base: "send", pastSimple: "sent", pastParticiple: "sent", meaningAr: "يرسل", example: "I sent her a message.", level: "easy" },
  { base: "build", pastSimple: "built", pastParticiple: "built", meaningAr: "يبني", example: "They built a new house.", level: "easy" },

  // ===== متوسط =====
  { base: "break", pastSimple: "broke", pastParticiple: "broken", meaningAr: "يكسر", example: "He broke the window.", level: "medium" },
  { base: "choose", pastSimple: "chose", pastParticiple: "chosen", meaningAr: "يختار", example: "She chose the blue dress.", level: "medium" },
  { base: "drive", pastSimple: "drove", pastParticiple: "driven", meaningAr: "يقود", example: "He drove to work.", level: "medium" },
  { base: "drink", pastSimple: "drank", pastParticiple: "drunk", meaningAr: "يشرب", example: "I drank some water.", level: "medium" },
  { base: "fall", pastSimple: "fell", pastParticiple: "fallen", meaningAr: "يسقط", example: "She fell off the bike.", level: "medium" },
  { base: "fly", pastSimple: "flew", pastParticiple: "flown", meaningAr: "يطير", example: "The bird flew away.", level: "medium" },
  { base: "forget", pastSimple: "forgot", pastParticiple: "forgotten", meaningAr: "ينسى", example: "I forgot my keys.", level: "medium" },
  { base: "grow", pastSimple: "grew", pastParticiple: "grown", meaningAr: "ينمو", example: "The plant grew quickly.", level: "medium" },
  { base: "hide", pastSimple: "hid", pastParticiple: "hidden", meaningAr: "يختبئ", example: "The cat hid under the bed.", level: "medium" },
  { base: "hit", pastSimple: "hit", pastParticiple: "hit", meaningAr: "يضرب", example: "The ball hit the wall.", level: "medium" },
  { base: "lose", pastSimple: "lost", pastParticiple: "lost", meaningAr: "يخسر / يفقد", example: "We lost the match.", level: "medium" },
  { base: "mean", pastSimple: "meant", pastParticiple: "meant", meaningAr: "يعني", example: "I meant what I said.", level: "medium" },
  { base: "ride", pastSimple: "rode", pastParticiple: "ridden", meaningAr: "يركب", example: "She rode her bicycle.", level: "medium" },
  { base: "ring", pastSimple: "rang", pastParticiple: "rung", meaningAr: "يرن", example: "The phone rang loudly.", level: "medium" },
  { base: "rise", pastSimple: "rose", pastParticiple: "risen", meaningAr: "يرتفع", example: "The sun rose early.", level: "medium" },
  { base: "shoot", pastSimple: "shot", pastParticiple: "shot", meaningAr: "يطلق النار", example: "He shot the ball into the goal.", level: "medium" },
  { base: "show", pastSimple: "showed", pastParticiple: "shown", meaningAr: "يُظهر", example: "She showed me her photos.", level: "medium" },
  { base: "sing", pastSimple: "sang", pastParticiple: "sung", meaningAr: "يغني", example: "They sang a beautiful song.", level: "medium" },
  { base: "sleep", pastSimple: "slept", pastParticiple: "slept", meaningAr: "ينام", example: "I slept for eight hours.", level: "medium" },
  { base: "spend", pastSimple: "spent", pastParticiple: "spent", meaningAr: "يصرف / يقضي وقتًا", example: "We spent the weekend at home.", level: "medium" },
  { base: "steal", pastSimple: "stole", pastParticiple: "stolen", meaningAr: "يسرق", example: "Someone stole his bag.", level: "medium" },
  { base: "swim", pastSimple: "swam", pastParticiple: "swum", meaningAr: "يسبح", example: "We swam in the sea.", level: "medium" },
  { base: "teach", pastSimple: "taught", pastParticiple: "taught", meaningAr: "يعلّم", example: "She taught us English.", level: "medium" },
  { base: "throw", pastSimple: "threw", pastParticiple: "thrown", meaningAr: "يرمي", example: "He threw the ball.", level: "medium" },
  { base: "understand", pastSimple: "understood", pastParticiple: "understood", meaningAr: "يفهم", example: "I understood the lesson.", level: "medium" },
  { base: "wake", pastSimple: "woke", pastParticiple: "woken", meaningAr: "يستيقظ", example: "He woke up early.", level: "medium" },
  { base: "wear", pastSimple: "wore", pastParticiple: "worn", meaningAr: "يرتدي", example: "She wore a red dress.", level: "medium" },
  { base: "win", pastSimple: "won", pastParticiple: "won", meaningAr: "يفوز", example: "Our team won the game.", level: "medium" },
  { base: "draw", pastSimple: "drew", pastParticiple: "drawn", meaningAr: "يرسم", example: "The child drew a house.", level: "medium" },
  { base: "catch", pastSimple: "caught", pastParticiple: "caught", meaningAr: "يمسك / يلحق", example: "She caught the ball.", level: "medium" },
  { base: "cut", pastSimple: "cut", pastParticiple: "cut", meaningAr: "يقطع", example: "He cut the paper.", level: "medium" },
  { base: "dig", pastSimple: "dug", pastParticiple: "dug", meaningAr: "يحفر", example: "They dug a hole in the garden.", level: "medium" },
  { base: "shut", pastSimple: "shut", pastParticiple: "shut", meaningAr: "يغلق", example: "She shut the door quietly.", level: "medium" },
  { base: "set", pastSimple: "set", pastParticiple: "set", meaningAr: "يضبط / يضع", example: "He set the table for dinner.", level: "medium" },

  // ===== صعب (أقل شيوعًا / أشكال غير متوقعة) =====
  { base: "bear", pastSimple: "bore", pastParticiple: "born/borne", meaningAr: "يتحمل / يلد", example: "She bore the pain silently.", level: "hard" },
  { base: "beat", pastSimple: "beat", pastParticiple: "beaten", meaningAr: "يهزم / يضرب", example: "They beat the other team.", level: "hard" },
  { base: "bend", pastSimple: "bent", pastParticiple: "bent", meaningAr: "يثني", example: "He bent the metal bar.", level: "hard" },
  { base: "bind", pastSimple: "bound", pastParticiple: "bound", meaningAr: "يربط", example: "They bound the boxes with rope.", level: "hard" },
  { base: "bite", pastSimple: "bit", pastParticiple: "bitten", meaningAr: "يعض", example: "The dog bit the postman.", level: "hard" },
  { base: "bleed", pastSimple: "bled", pastParticiple: "bled", meaningAr: "ينزف", example: "His hand bled after the cut.", level: "hard" },
  { base: "blow", pastSimple: "blew", pastParticiple: "blown", meaningAr: "ينفخ / تهب (الريح)", example: "The wind blew hard.", level: "hard" },
  { base: "breed", pastSimple: "bred", pastParticiple: "bred", meaningAr: "يربّي (حيوانات)", example: "They breed horses on the farm.", level: "hard" },
  { base: "broadcast", pastSimple: "broadcast", pastParticiple: "broadcast", meaningAr: "يبث", example: "The channel broadcast the news live.", level: "hard" },
  { base: "burst", pastSimple: "burst", pastParticiple: "burst", meaningAr: "ينفجر", example: "The balloon burst suddenly.", level: "hard" },
  { base: "cast", pastSimple: "cast", pastParticiple: "cast", meaningAr: "يلقي / يرمي", example: "He cast his fishing line.", level: "hard" },
  { base: "cling", pastSimple: "clung", pastParticiple: "clung", meaningAr: "يتشبث", example: "The child clung to her mother.", level: "hard" },
  { base: "creep", pastSimple: "crept", pastParticiple: "crept", meaningAr: "يزحف", example: "The cat crept slowly.", level: "hard" },
  { base: "deal", pastSimple: "dealt", pastParticiple: "dealt", meaningAr: "يتعامل مع", example: "She dealt with the problem calmly.", level: "hard" },
  { base: "dive", pastSimple: "dove/dived", pastParticiple: "dived", meaningAr: "يغطس", example: "He dove into the pool.", level: "hard" },
  { base: "feed", pastSimple: "fed", pastParticiple: "fed", meaningAr: "يطعم", example: "She fed the baby.", level: "hard" },
  { base: "fight", pastSimple: "fought", pastParticiple: "fought", meaningAr: "يقاتل", example: "The soldiers fought bravely.", level: "hard" },
  { base: "flee", pastSimple: "fled", pastParticiple: "fled", meaningAr: "يهرب", example: "The thief fled the scene.", level: "hard" },
  { base: "forbid", pastSimple: "forbade", pastParticiple: "forbidden", meaningAr: "يمنع", example: "Smoking is forbidden here.", level: "hard" },
  { base: "forgive", pastSimple: "forgave", pastParticiple: "forgiven", meaningAr: "يسامح", example: "She forgave her friend.", level: "hard" },
  { base: "freeze", pastSimple: "froze", pastParticiple: "frozen", meaningAr: "يتجمد", example: "The lake froze in winter.", level: "hard" },
  { base: "grind", pastSimple: "ground", pastParticiple: "ground", meaningAr: "يطحن", example: "She ground the coffee beans.", level: "hard" },
  { base: "hang", pastSimple: "hung", pastParticiple: "hung", meaningAr: "يعلّق", example: "He hung the picture on the wall.", level: "hard" },
  { base: "kneel", pastSimple: "knelt", pastParticiple: "knelt", meaningAr: "يركع", example: "He knelt down to pray.", level: "hard" },
  { base: "lay", pastSimple: "laid", pastParticiple: "laid", meaningAr: "يضع / يبيض", example: "She laid the baby on the bed.", level: "hard" },
  { base: "lead", pastSimple: "led", pastParticiple: "led", meaningAr: "يقود", example: "He led the team to victory.", level: "hard" },
  { base: "lean", pastSimple: "leant/leaned", pastParticiple: "leant/leaned", meaningAr: "يستند", example: "She leaned against the wall.", level: "hard" },
  { base: "leap", pastSimple: "leapt/leaped", pastParticiple: "leapt/leaped", meaningAr: "يقفز", example: "The cat leapt onto the table.", level: "hard" },
  { base: "lend", pastSimple: "lent", pastParticiple: "lent", meaningAr: "يقرض", example: "He lent me his book.", level: "hard" },
  { base: "lie", pastSimple: "lay", pastParticiple: "lain", meaningAr: "يستلقي", example: "She lay on the sofa.", level: "hard" },
  { base: "light", pastSimple: "lit", pastParticiple: "lit", meaningAr: "يضيء / يشعل", example: "He lit a candle.", level: "hard" },
  { base: "quit", pastSimple: "quit", pastParticiple: "quit", meaningAr: "يستقيل / يترك", example: "She quit her job.", level: "hard" },
  { base: "seek", pastSimple: "sought", pastParticiple: "sought", meaningAr: "يبحث عن", example: "They sought help from experts.", level: "hard" },
  { base: "shake", pastSimple: "shook", pastParticiple: "shaken", meaningAr: "يهز", example: "The earthquake shook the building.", level: "hard" },
  { base: "shine", pastSimple: "shone", pastParticiple: "shone", meaningAr: "يلمع / يشرق", example: "The sun shone brightly.", level: "hard" },
  { base: "shrink", pastSimple: "shrank", pastParticiple: "shrunk", meaningAr: "ينكمش", example: "My shirt shrank in the wash.", level: "hard" },
  { base: "spin", pastSimple: "spun", pastParticiple: "spun", meaningAr: "يدور", example: "The wheel spun fast.", level: "hard" },
  { base: "spit", pastSimple: "spat", pastParticiple: "spat", meaningAr: "يبصق", example: "He spat on the ground.", level: "hard" },
  { base: "split", pastSimple: "split", pastParticiple: "split", meaningAr: "يشق / يقسم", example: "They split the bill.", level: "hard" },
  { base: "spread", pastSimple: "spread", pastParticiple: "spread", meaningAr: "ينتشر / يفرد", example: "She spread the butter on the bread.", level: "hard" },
  { base: "spring", pastSimple: "sprang", pastParticiple: "sprung", meaningAr: "يقفز فجأة", example: "The cat sprang onto the table.", level: "hard" },
  { base: "stick", pastSimple: "stuck", pastParticiple: "stuck", meaningAr: "يلصق / يعلق", example: "The stamp stuck to the envelope.", level: "hard" },
  { base: "sting", pastSimple: "stung", pastParticiple: "stung", meaningAr: "يلسع", example: "A bee stung his arm.", level: "hard" },
  { base: "stink", pastSimple: "stank", pastParticiple: "stunk", meaningAr: "له رائحة كريهة", example: "The trash stank badly.", level: "hard" },
  { base: "strike", pastSimple: "struck", pastParticiple: "struck", meaningAr: "يضرب / يصيب", example: "Lightning struck the tree.", level: "hard" },
  { base: "swear", pastSimple: "swore", pastParticiple: "sworn", meaningAr: "يقسم", example: "He swore to tell the truth.", level: "hard" },
  { base: "sweep", pastSimple: "swept", pastParticiple: "swept", meaningAr: "يكنس", example: "She swept the floor.", level: "hard" },
  { base: "swell", pastSimple: "swelled", pastParticiple: "swollen", meaningAr: "يتورم", example: "His ankle swelled after the fall.", level: "hard" },
  { base: "swing", pastSimple: "swung", pastParticiple: "swung", meaningAr: "يتأرجح", example: "The children swung on the swings.", level: "hard" },
  { base: "tear", pastSimple: "tore", pastParticiple: "torn", meaningAr: "يمزق", example: "He tore the paper in half.", level: "hard" },
  { base: "weep", pastSimple: "wept", pastParticiple: "wept", meaningAr: "يبكي", example: "She wept quietly.", level: "hard" },
  { base: "wind", pastSimple: "wound", pastParticiple: "wound", meaningAr: "يلف / يدور", example: "He wound the clock.", level: "hard" },
  { base: "withdraw", pastSimple: "withdrew", pastParticiple: "withdrawn", meaningAr: "يسحب", example: "She withdrew money from the bank.", level: "hard" },
  { base: "wring", pastSimple: "wrung", pastParticiple: "wrung", meaningAr: "يعصر", example: "He wrung the wet towel.", level: "hard" },
];
